### ISSUE TITLE
Parametrización de correlativo

### ISSUE THREAD

**Issue by flex-devs** [suscerte/aponwao#6]
Se requiere posibilidad de parametrizar el correlativo desde archivo de configuración.

**Comment by flex-devs** [comment]
Se parametrizaron los valores siguientes en el archivo "packer/aponwao/aponwao-preferencias/preferences-aplication.properties":

```
appearance.correlativo.font.bold=false
appearance.correlativo.font.italics=false
appearance.correlativo.posX=35
appearance.correlativo.posY=742
```

Queda pendiente la revisión de la clase flex.aponwao.gui.sections.main.helpers.FirmarPDFHelper por parte de otro compañero:

```
if (cursiva) cb.setTextMatrix(1, 0, 25, 1, 0, 0);
```

**Comment by axeliodiaz** [comment]
Se resuelve la incidencia con el siguiente commit: https://github.com/suscerte/aponwao/issues/6#issuecomment-97291406
