### ISSUE TITLE
Generación de CSV para duplicados

### ISSUE THREAD

**Issue by flex-devs** [suscerte/aponwao#7]
Se requiere la generación de un CSV para la firma de duplicados con el siguiente formato:

```
<correlativo>;<CN_Firmante>;en fecha <fecha_firma>
```

**Comment by flex-developments** [comment]
Resuelto!
Se implementó la generación automática de un archivo CSV que resuma las operaciones de firma realizadas durante un proceso de firma de duplicados. La activación de esta función se realiza en el archivo **"packer/aponwao/aponwao-preferencias/preferences-aplication.properties"** en la key:
```
duplicado.csv.enable
```

**Comment by flex-devs** [comment]
Resuelto!
Se implementó la generación automática de un archivo CSV que resuma las operaciones de firma realizadas durante un proceso de firma de duplicados. La activación de esta función se realiza en el archivo **"packer/aponwao/aponwao-preferencias/preferences-aplication.properties"** en la key:

```
duplicado.csv.enable
```
